<img align="center" src="https://iili.io/3wI8gI.png" style="height:90px" style="width:30px"/>

# T-tests Lab

A t-test is used to compare the means of two groups. Below you'll find three different types of t-tests listed: 
- **1-sample t-test:** Used to compare the mean of a sample with a known (or made up) population mean
    - I.e.: Are people attending Nod Coding Bootcamp spending more than 40 hours per week coding?


- **Unpaired/Independent 2-sample t-test:** Used to compare the mean of two samples drawn from two separate/independent populations
    - I.e. are people who have attended Nod Coding Bootcamp spending more time coding than people who have attended an online Coding Bootcamp


- **Paired/Dependent 2-sample t-test:** Most commonly used to compare the mean of two samples drawn from the same population but where each subject/entity in the sample have been measured twice, usually before and after some treatment. (There are other variations to when a paired t-test is used but let's not get into those!)
    - I.e. are people who have attended Nod Coding Bootcamp spending more time coding after the bootcamp compared to how much time they spent coding before having attended the Bootcamp. 
    
    
The python library scipy provides access to functions with the above mentioned t-tests. Follow the link to see an overview of the statistical tests available in the scipy library - https://docs.scipy.org/doc/scipy/reference/stats.html#statistical-tests

Each t-test function in scipy returns a T-statistic and the associated p-value. 

Read more about t-tests [here](https://www.statisticshowto.com/probability-and-statistics/t-test/) and [here](https://www.investopedia.com/terms/t/t-test.asp) and/or google on your own!

# Checklist for guidance

You can use this checklist as guidance. You don't necessarily have to follow every step and also, following every step is not necessarily sufficient. Rather, look at this checklist as a helpful resource. Ultimately you are resonsible for conducting your analysis in the ways you see fit. 

- Make a clear description of the population(s) (and the population mean, given that it is known) 
- Make a clear description of your sample(s)
- Generate H0 and H1
- Decide which ttest is the most appropriate
- Decide if you have a two-sided or 1-sided hypothesis and if 1-sided decide the direction
- Decide alpha-level / level of significance
- Prepare sample data
- Import the function for your chosen ttest from scipy
- Run the ttest with your data
    - Specify parameters correctly in the ttest (if necessary)
- Evaluate the result i.e. Keep or reject your H0/H1

**Note:** For all questions in this lab, Use a 5% alpha level if a different alpha level is not specified

___

# Part 1 | Stats Quiz Scores, before and after theory session

In the first part of this lab we will work with mock data about the performance of Nod students on a stats quiz. We are assuming that the same students took the same quiz twice, before and after having attended a theory session. We want to investigate whether the results were significantly better the second time the students took the quiz.

We have created two different mock datasets:
- "stats_quiz_n10.csv" where there are 10 students participating in the experiment
- "stats_quiz_n30.csv" where there are 30 students participating in the experiment

## 1. stats_quiz_n10

Did students have a significantly better performance the second time they took the quiz? (after having attended Gustavs theory session about the concepts asked about in the quiz)

**Note:** You should do a 1-sided hypothesis. Make sure to adjust the "alternative" parameter in the t-test accordingly

In [1]:
# Start with importing pandas and create a df from the file "stats_quiz_n10.csv"

In [3]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [ ]:
df = pd.read_csv("stats_quiz_n10.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  10 non-null     int64
 1   test_1   10 non-null     int64
 2   test_2   10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

In [ ]:
# h0 = test_1 avg <= test 2 avg /// h1 = test_2 avg > test_1 avg

In [10]:
df["difference"] = df["test_2"] - df["test_1"]
df.head()

   user_id  test_1  test_2  difference
0        1      14      11          -3
1        2      15      18           3
2        3      11      11           0
3        4      11      19           8
4        5      14      18           4

In [ ]:
dof = len(df) - 1 
dof

9

In [ ]:
t_critical = 1.833

In [9]:
t = df["difference"].mean() / (df["difference"].std()) / np.sqrt(len(df))
t

np.float64(0.13298717802724688)

In [ ]:
t > t_critical

np.False_

## 2. stats_quiz_n30

Same specifications as in the previous question, only this time we have 30 students included in the mock experiment

In [73]:
# Start with creating a df from the file "stats_quiz_n30.csv"
df = pd.read_csv("stats_quiz_n30.csv")
df

    user_id  test_1  test_2
0         1      17      11
1         2      13      19
2         3      14      15
3         4      16      13
4         5      16      14
5         6      15      13
6         7      13      17
7         8      15      16
8         9      16      15
9        10      11      12
10       11      14      15
11       12      16      16
12       13      14      13
13       14      17      14
14       15      14      19
15       16      14      16
16       17      13      16
17       18      11      12
18       19      15      17
19       20      16      16
20       21      14      16
21       22      12      11
22       23      13      15
23       24      14      15
24       25      14      17
25       26      11      12
26       27      14      17
27       28      16      19
28       29      14      18
29       30      14      13

In [39]:
df["difference"] = df["test_2"] - df["test_1"]

In [40]:
df.head()

   user_id  test_1  test_2  difference
0        1      17      11          -6
1        2      13      19           6
2        3      14      15           1
3        4      16      13          -3
4        5      16      14          -2

In [41]:
dof = len(df) - 1 
dof

29

In [42]:
t_critical = 1.699

In [45]:
t = df["difference"].mean() / ((df["difference"].std()) / np.sqrt(len(df)))
t

np.float64(1.828417486455131)

In [46]:
t > t_critical

np.True_

___

# Part 2 | Looking into sek/sqm for apartments sold in Stockholm

In part 2 we will work with data scraped from Hemnet about apartments sold in Stockholm in the years 2013-2020. We will focus specifically on the `sek_sqm` column and compare the mean sek/sqm for different subsets of the data.

In [75]:
# Create a df from the file "sthlm_eng.csv"
df = pd.read_csv("sthlm_eng (1).csv")

In [49]:
df.head()

,address,area,sqm,rooms,broker,monthly_fee,price_sek,date,pct_change,street_id,street_name,municipality,sek_sqm,yr_sold,mo_sold,mo_yr_sold
0,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",114.0,3.5,Fastighetsbyrån Stockholm - Vasastan,6769.0,7600000,2018-04-13,-5,475079,Gamla Brogatan,Stockholms kommun,66666,2018,4,2018-04-01
1,"Gamla Brogatan 25, 2 tr","Vasastan- City/ Norrmalm,",71.0,2.0,Mäklarhuset Stockholm Innerstan,4696.0,5050000,2016-06-23,4,475079,Gamla Brogatan,Stockholms kommun,71126,2016,6,2016-06-01
2,Gamla Brogatan 25,"Vasastan- City/ Norrmalm,",102.0,4.0,Mäklarhuset Stockholm Innerstan,6519.0,6950000,2016-04-29,1,475079,Gamla Brogatan,Stockholms kommun,68137,2016,4,2016-04-01
3,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",107.0,4.0,Fastighetsbyrån Stockholm - Vasastan,6713.0,7150000,2015-11-26,2,475079,Gamla Brogatan,Stockholms kommun,66822,2015,11,2015-11-01
4,"Drottninggatan 114 A, 3 tr","Vasastan - Norrmalm,",90.0,3.0,Bostadsrättsspecialisten,3822.0,8900000,2020-08-13,0,475084,Drottninggatan,Stockholms kommun,98888,2020,8,2020-08-01

In [76]:
df.dtypes

address             str
area                str
sqm             float64
rooms           float64
broker              str
monthly_fee     float64
price_sek         int64
date                str
pct_change        int64
street_id         int64
street_name         str
municipality        str
sek_sqm           int64
yr_sold           int64
mo_sold           int64
mo_yr_sold          str
dtype: object

In [58]:
test = "30-07-1997"
test = test.split("-")[-1]
test

'1997'

## 1. Folkungagatan

### 1.1 Is the average sek/sqm for apartments sold on Folkungagatan in 2020 significantly different from the population mean?

The average sek/sqm for apartments sold in central Stockholm was 89000 SEK in 2020. 

Now we're going to compare the mean sek/sqm for apartments sold on the street Folkungagatan and compare that with the population mean of 89000.

**Note:** In this question you should do a two-sided hypothesis

In [77]:
#H0 stockholm sqmt avg = folkingagatan avg
#H1 folkungagatan avg ≠ stockholm avg 
df

,address,area,sqm,rooms,broker,monthly_fee,price_sek,date,pct_change,street_id,street_name,municipality,sek_sqm,yr_sold,mo_sold,mo_yr_sold
0,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",114.0,3.5,Fastighetsbyrån Stockholm - Vasastan,6769.0,7600000,2018-04-13,-5,475079,Gamla Brogatan,Stockholms kommun,66666,2018,4,2018-04-01
1,"Gamla Brogatan 25, 2 tr","Vasastan- City/ Norrmalm,",71.0,2.0,Mäklarhuset Stockholm Innerstan,4696.0,5050000,2016-06-23,4,475079,Gamla Brogatan,Stockholms kommun,71126,2016,6,2016-06-01
2,Gamla Brogatan 25,"Vasastan- City/ Norrmalm,",102.0,4.0,Mäklarhuset Stockholm Innerstan,6519.0,6950000,2016-04-29,1,475079,Gamla Brogatan,Stockholms kommun,68137,2016,4,2016-04-01
3,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",107.0,4.0,Fastighetsbyrån Stockholm - Vasastan,6713.0,7150000,2015-11-26,2,475079,Gamla Brogatan,Stockholms kommun,66822,2015,11,2015-11-01
4,"Drottninggatan 114 A, 3 tr","Vasastan - Norrmalm,",90.0,3.0,Bostadsrättsspecialisten,3822.0,8900000,2020-08-13,0,475084,Drottninggatan,Stockholms kommun,98888,2020,8,2020-08-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57931,"Lindevägen 56, 3 tr","Enskede Gård,",74.5,3.0,Svensk Fastighetsförmedling,5002.0,2740000,2014-04-10,19,476350,Lindevägen,Stockholms kommun,36778,2014,4,2014-04-01
57932,Lindevägen 56,"Enskede Gård,",63.0,2.0,Svensk Fastighetsförmedling,3960.0,1905000,2014-02-28,12,476350,Lindevägen,Stockholms kommun,30238,2014,2,2014-02-01
57933,"Lindevägen 44, 2tr","Enskede Gård,",107.0,4.0,Fastighetsbyrån Enskede,6977.0,3720000,2013-08-22,6,476350,Lindevägen,Stockholms kommun,34766,2013,8,2013-08-01
57934,Lindevägen 50,"Enskede Gård,",61.5,2.0,Mäklarhuset Enskede,4221.0,2100000,2013-03-07,11,476350,Lindevägen,Stockholms kommun,34146,2013,3,2013-03-01
57935,Lindevägen 54,"Enskede Gård,",75.5,3.0,Mäklarhuset Enskede,5060.0,2290000,2013-01-15,0,476350,Lindevägen,Stockholms kommun,30331,2013,1,2013-01-01

In [87]:
# not needed x1 = df.loc[(df["municipality"] == "Stockholms kommun") & ~(df["street_name"].str.contains("Folkungagatan"))]["sek_sqm"]
x = df.loc[df["street_name"].str.contains("Folkungagatan") & (df["yr_sold"] == 2020)]["sek_sqm"]

In [93]:
df.loc[df["area"].str.lower().str.contains("stockholm")]

,address,area,sqm,rooms,broker,monthly_fee,price_sek,date,pct_change,street_id,street_name,municipality,sek_sqm,yr_sold,mo_sold,mo_yr_sold
64,"Drottninggatan 73A, 3tr","Stockholm/city,",29.0,1.0,Mäklarhuset Stockholm Innerstan,618.0,3400000,2015-04-01,31,475084,Drottninggatan,Stockholms kommun,117241,2015,4,2015-04-01
129,Kungsgatan 80 A,"Stockholm,",42.0,1.5,Svensk Fastighetsförmedling Sthlm Kungsholmen,1650.0,4075000,2016-08-10,9,475094,Kungsgatan,Stockholms kommun,97023,2016,8,2016-08-01
196,Dalagatan 78A,"Stockholm - Vasastan,",76.3,2.0,BOSTHLM,2685.0,6900000,2020-08-25,6,475099,Dalagatan,Stockholms kommun,90432,2020,8,2020-08-01
380,"Dalagatan 68B, 2 tr","Stockholm,",43.0,2.0,Svensk Fastighetsförmedling Sthlm Vasastan,2141.0,4450000,2017-08-15,11,475099,Dalagatan,Stockholms kommun,103488,2017,8,2017-08-01
381,"Dalagatan 29, 1 tr","Stockholm/Vasastan,",74.0,3.0,Mäklarhuset Stockholm Innerstan,3316.0,6525000,2017-06-21,15,475099,Dalagatan,Stockholms kommun,88175,2017,6,2017-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55252,Timotejgatan 7,"Stockholm,",45.0,2.5,Svensk Fastighetsförmedling Sthlm Södermalm,2545.0,3400000,2019-03-30,-3,476261,Timotejgatan,Stockholms kommun,75555,2019,3,2019-03-01
55487,Fatburs Kvarngata 3,"Stockholm,",39.0,1.0,Alexander White,2686.0,2950000,2019-03-10,9,476274,Fatburs Kvarngata,Stockholms kommun,75641,2019,3,2019-03-01
55508,Fatburs Kvarngata 1,"Stockholm,",97.5,4.0,Svensk Fastighetsförmedling Sthlm Södermalm,5924.0,5800000,2018-03-29,-2,476274,Fatburs Kvarngata,Stockholms kommun,59487,2018,3,2018-03-01
55690,Marmorgatan 4,"Stockholm-Högalid,",43.5,2.0,Unika hem Sverige AB,2164.0,3500000,2019-09-12,6,476280,Marmorgatan,Stockholms kommun,80459,2019,9,2019-09-01
55704,Marmorgatan 11,"Stockholm - Södermalm,",29.0,1.0,Mäklarhuset Stockholm Innerstan,2300.0,2515000,2018-09-20,-3,476280,Marmorgatan,Stockholms kommun,86724,2018,9,2018-09-01

In [89]:
stats.ttest_1samp(a = x,popmean = 89000,alternative = "two-sided")

TtestResult(statistic=np.float64(1.8672137481924955), pvalue=np.float64(0.06940130382818818), df=np.int64(39))

### 1.2 Is the average sek/sqm for apartments sold on Folkungagatan in 2020 greater than the average sek/sqm for apartments sold in Central Stockholm in 2020?

**Note:** In this question you should do a one-sided hypothesis

In [94]:
stats.ttest_1samp(a = x,popmean = 89000,alternative = "greater")

TtestResult(statistic=np.float64(1.8672137481924955), pvalue=np.float64(0.03470065191409409), df=np.int64(39))

In [95]:
df.head()

,address,area,sqm,rooms,broker,monthly_fee,price_sek,date,pct_change,street_id,street_name,municipality,sek_sqm,yr_sold,mo_sold,mo_yr_sold
0,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",114.0,3.5,Fastighetsbyrån Stockholm - Vasastan,6769.0,7600000,2018-04-13,-5,475079,Gamla Brogatan,Stockholms kommun,66666,2018,4,2018-04-01
1,"Gamla Brogatan 25, 2 tr","Vasastan- City/ Norrmalm,",71.0,2.0,Mäklarhuset Stockholm Innerstan,4696.0,5050000,2016-06-23,4,475079,Gamla Brogatan,Stockholms kommun,71126,2016,6,2016-06-01
2,Gamla Brogatan 25,"Vasastan- City/ Norrmalm,",102.0,4.0,Mäklarhuset Stockholm Innerstan,6519.0,6950000,2016-04-29,1,475079,Gamla Brogatan,Stockholms kommun,68137,2016,4,2016-04-01
3,"Gamla Brogatan 25, 2tr","Vasastan - City/Norrmalm,",107.0,4.0,Fastighetsbyrån Stockholm - Vasastan,6713.0,7150000,2015-11-26,2,475079,Gamla Brogatan,Stockholms kommun,66822,2015,11,2015-11-01
4,"Drottninggatan 114 A, 3 tr","Vasastan - Norrmalm,",90.0,3.0,Bostadsrättsspecialisten,3822.0,8900000,2020-08-13,0,475084,Drottninggatan,Stockholms kommun,98888,2020,8,2020-08-01

### 1.3 Mean sek/sqm for 1 room apartments vs 2 room apartments on Folkungagatan (all years)

Is there a statistically significant difference between the mean sek/sqm price of 1 room apartments sold on folkungagatan between 2013-2020 compared to the mean sek/sqm price of 2 room apartments? 

**Note:** It's up to you to decide if you want to do a 1-sided or 2-sided hypothesis

In [ ]:
x1 = df.loc[df["street_name"].str.contains("Folkungagatan") & (df["rooms"] == 1)]["sek_sqm"]
x2 = df.loc[df["street_name"].str.contains("Folkungagatan") & (df["rooms"] == 2)]["sek_sqm"]
stats.ttest_ind(x1,x2)

TtestResult(statistic=np.float64(4.599358695545062), pvalue=np.float64(7.151076624388919e-06), df=np.float64(220.0))

### 1.4 Mean sek/sqm for 2 room apartments vs 3 room apartments on Folkungagatan (all years)

Is there a statistically significant difference between the mean sek/sqm price of 2 room apartments sold on folkungagatan between 2013-2020 compared to the mean sek/sqm price of 3 room apartments? 

**Note:** It's up to you to decide if you want to do a 1-sided or 2-sided hypothesis

In [ ]:
x1 = df.loc[df["street_name"].str.contains("Folkungagatan") & (df["rooms"] == 2)]["sek_sqm"]
x2 = df.loc[df["street_name"].str.contains("Folkungagatan") & (df["rooms"] == 3)]["sek_sqm"]
stats.ttest_ind(x1,x2)

### 1.5 Mean sek/sqm for 3 room apartments vs 4 room apartments on Folkungagatan (all years)

Is there a statistically significant difference between the mean sek/sqm price of 3 room apartments sold on folkungagatan between 2013-2020 compared to the mean sek/sqm price of 4 room apartments? 

**Note:** It's up to you to decide if you want to do a 1-sided or 2-sided hypothesis

In [ ]:
x1 = df.loc[df["street_name"].str.contains("Folkungagatan") & (df["rooms"] == 3)]["sek_sqm"]
x2 = df.loc[df["street_name"].str.contains("Folkungagatan") & (df["rooms"] == 4)]["sek_sqm"]
stats.ttest_ind(x1,x2)

# 2. Erstagatan, Doktor Abelins gata & Hornsgatan

### 2.1 Check if the mean for sek/sqm on "Erstagatan" is significantly greater than the mean sek/sqm on "Hornsgatan" (all years)

In [101]:
x1 = df.loc[df["street_name"].str.contains("Erstagatan")]["sek_sqm"]
x2 = df.loc[df["street_name"].str.contains("Hornsgatan")]["sek_sqm"]
stats.ttest_ind(x1,x2,alternative="greater")

TtestResult(statistic=np.float64(1.8763135529529724), pvalue=np.float64(0.030524989275850515), df=np.float64(665.0))

### 2.2 Check if the mean for sek/sqm on "Doktor Abelins gata" is significantly greater than the mean sek/sqm on "Hornsgatan" (all years)

In [102]:
x1 = df.loc[df["street_name"].str.contains("Doktor Abelins gata")]["sek_sqm"]
x2 = df.loc[df["street_name"].str.contains("Hornsgatan")]["sek_sqm"]
stats.ttest_ind(x1,x2,alternative="greater")

TtestResult(statistic=np.float64(1.1644644224524985), pvalue=np.float64(0.12236897922167944), df=np.float64(553.0))

### 2.3 Explain!

If we look at the mean sek/sqm for Erstagatan and Doktor Abelins gata we will see that the mean is higher for Doktor Abelins gata. However when we did our ttests we could state that the mean price for Erstagatan was greater than that of Hornsgatan with statistical significance but we could not do this for the mean sek/sqm for Doktor Abelins gata, even though the mean sek/sqm for Doktor Abelins gata is bigger than the mean sek/sqm for Erstagatan.

Provide 2 factors that help explain why this happens

ers < dok
ers > Horns

In [ ]:
#cause sample size and and dof

# GOOD JOB, lab finished

___

# Bonus Challenges

## Constructing Confidence Intervals

Confidence intervals is a closely related concept to t-tests. A confidence interval gives us an estimate of an interval containing the true mean of the population. I.e. for a 95% confidence interval, we are 95% sure that the true mean of the population is within the esitmated confidence interval. 

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval) and/or google on your own

## Introducing the dataset

In the bonus challenges 1-3 you will work with data stored in the file "salaries_chicago.csv"

The dataset stores information about salaries for people employeed by the City of Chicago

Take a minute to inspect the data

In [4]:
df = pd.read_csv("salaries_chicago.csv")

In [5]:
df.describe()

       Typical Hours  Annual Salary  Hourly Rate
count    8022.000000   25161.000000  8022.000000
mean       34.507604   86786.999790    32.788558
std         9.252077   21041.354602    12.112573
min        10.000000    7200.000000     2.650000
25%        20.000000   76266.000000    21.200000
50%        40.000000   90024.000000    35.600000
75%        40.000000   96060.000000    40.200000
max        40.000000  300000.000000   109.000000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 33183 entries, 0 to 33182
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               33183 non-null  str
 1   Job Titles         33183 non-null  str
 2   Department         33183 non-null  str
 3   Full or Part-Time  33183 non-null  str
 4   Salary or Hourly   33183 non-null  str
 5   Typical Hours      8022 non-null   float64
 6   Annual Salary      25161 non-null  float64
 7   Hourly Rate        8022 non-null   float64
dtypes: float64(3), str(5)
memory usage: 2.0 MB

In [7]:
df.dtypes

Name                     str
Job Titles               str
Department               str
Full or Part-Time        str
Salary or Hourly         str
Typical Hours        float64
Annual Salary        float64
Hourly Rate          float64
dtype: object

## 1. Construct a 95% CI for the mean hourly wage of all hourly workers

We will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

A function for computing the confidence interval can be found in the SciPy library with the name `t.interval`. You can find the documentation for this function [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html).

To compute the 95% confidence interval for the hourly wage:
- use 0.95 for the confidence level/alpha level 
- (number of rows - 1) for degrees of freedom
- the mean of the sample for the location parameter 
- the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in the SciPy library.

In [8]:
data = df["Hourly Rate"].dropna()

interval = stats.t.interval(
    0.95,
    df=len(data) - 1,
    loc=data.mean(),
    scale=stats.sem(data)
)
interval

(np.float64(32.52345834488425), np.float64(33.05365708767623))

7788

## 2. Construct a 95% CI for the mean annual salary for all salaried employees in the Police Department

In [14]:
data = df.loc[df["Department"] == "POLICE"]["Annual Salary"].dropna()

interval = stats.t.interval(
    0.95,
    df=len(data) - 1,
    loc=data.mean(),
    scale=stats.sem(data)
)
interval

(np.float64(86177.05631531784), np.float64(86795.77269094894))

In [11]:
df["Department"].unique

<bound method Series.unique of 0                  POLICE
1                  POLICE
2        GENERAL SERVICES
3             WATER MGMNT
4                    OEMC
               ...
33178              POLICE
33179              POLICE
33180              POLICE
33181              POLICE
33182                DoIT
Name: Department, Length: 33183, dtype: str>

## 3. Do question 1 & 2, but now calculate the CI using Bootstrapping

[Statquest Video: Bootstrapping main ideas](https://www.youtube.com/watch?v=Xz0x-8-cgaQ)

Compare the results between the Bootstrapped CI and the CI calculated from formula for the two questions. Small, medium or big differences?

## 4. Redo question 1 & 2 from Part 1 of the original lab, but now calculate the p-values using Bootstrapping

[Statquest Video: Using Bootstrapping to Calculate p-values](https://www.youtube.com/watch?v=N4ZQQqyIf6k)

The questions are repeated below:

### 1. stats_quiz_n10

Did students have a significantly better performance the second time they took the quiz? (after having attended Gustavs theory session about the concepts asked about in the quiz)

**Note:** You should do a 1-sided hypothesis. Make sure to adjust the "alternative" parameter in the t-test accordingly


### 2. stats_quiz_n30

Same specifications as in the previous question, only this time we have 30 students included in the mock experiment

___

Compare the results between the Bootstrapped p-values and the p-values calculated from formula for the two questions. Small, medium or big differences?